### ISSUE TITLE
modulerror

### ISSUE THREAD

**Issue by sakib501** [andrewschenck/paramiko-jump#16]
i am trying this to login to switch and get some show version. there is a jump host in between. that is 2 factor. first it takes a password then i have to type 1 then some authentication comes in cell phone i have to approve then i can login to jump host. 

i am getting this modulerror. 

ModuleNotFoundError: No module named 'paramiko_jump'

any idea how to resolve this?

**Comment by andrewschenck** [comment]
Did you install the paramiko_jump package from this git repo, and ensure it's in your PYTHONPATH?

**Comment by andrewschenck** [comment]
You can now 'pip install paramiko-jump' in order to get it into your Python environment -- even easier than having to manually pip install the path to this repo.
