### ISSUE TITLE
Inherited Import Causing Typing and Validation Errors

### ISSUE THREAD

**Issue by prokopto-dev** [andrewschenck/paramiko-jump#17]
Hey all;

Just a small nit-pick, but when using packages like `mypy`, `pylance`, and `pyright`, the `SSH_PORT` variable grabbed from `paramiko.client` throws an error.

Line in question is here:
```python
from paramiko.client import SSH_PORT, SSHClient
``` 
The resolution is basically just to throw in another import line from the original source within `paramiko.config`:

```python
from paramiko.client import SSHClient
from paramiko.config import SSH_PORT
```

--- 

Will attach a PR to this for the resolution.

**Comment by andrewschenck** [comment]
Gotcha. Makes sense, though I never encountered that myself. I merged your PR. Andrew On May 17, 2024, at 13:17, Courtney Caldwell ***@***.***> wrote:﻿
Hey all;
Just a small nit-pick, but when using packages like mypy, pylance, and pyright, the SSH_PORT variable grabbed from paramiko.client throws an error.
Line in question is here:
from paramiko.client import SSH_PORT, SSHClient
The resolution is basically just to throw in another import line from the original source within paramiko.config:
from paramiko.client import SSHClient
from paramiko.config import SSH_PORT

Will attach a PR to this for the resolution.

**Comment by prokopto-dev** [comment]
Appreciated, @andrewschenck ! It's because sometimes those tools don't follow non-definition imports in submodules, so since `SSH_PORT` is defined in the Config submodule but imported into the Client submodule, some tools throw the error. More permissive typing implementations are perfectly fine with it, and sometimes there's config to allow it too;
