### ISSUE TITLE
Regarding _Host

### ISSUE THREAD

**Issue by prokopto-dev** [andrewschenck/paramiko-jump#20]
In the `client.py` file, there is a variable `_Host`:

```python

_Host = Union[AnyStr, Tuple[AnyStr, int]]
_Prompt = Tuple[AnyStr, bool]
```

It's used like its friend, `_Prompt`, as a representation of a complex type, in this case a Union between either an `AnyStr` or a tuple of `AnyStr` and a `bool`.

I understand, implicitly, what it is:

It represents either a hostname/IP, OR a hostname/IP combined with the `SSH_PORT` you expect to connect over on that particular host.

Obviously it's not used anywhere right now;

I'd be happy to write up an implementation for it, but I'm curious where it was intended to be used, or if it is a deprecated variable.

**Comment by andrewschenck** [comment]
You're not wrong about what the original intent was, but it was actually a snippet of a bigger bit of code that I originally ripped this from, and I'm not even sure why it got included in this initially -- because, as you point out, it's not even being used.
